import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/custom/navbar";
import Footer from "@/components/custom/footer";
import { Poppins } from 'next/font/google'

const poppins = Poppins({
    weight: '400',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={poppins.className}
            >
                <div className="flex flex-col justify-between">
                    <div className="bg-white-2 h-full">
                        <div>
                            <Navbar />
                            <div>
                                {children}
                            </div>
                        </div>
                        <Footer />

                    </div>
                </div>
            </body>
        </html>
    );
}
